/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package excerciseone.GUI;

import excerciseone.BLL.Common;
import excerciseone.DTO.AccountSchool;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author peter
 */
public class frm0003 extends javax.swing.JFrame {

    private AccountSchool accurent;
    
    /**
     * Creates new form frm0002
     */
    public frm0003() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        timecurrents = new javax.swing.JLabel();
        btnchangepass = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Management Study");
        setLocation(new java.awt.Point(150, 50));
        setPreferredSize(new java.awt.Dimension(1024, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(129, 211, 227));
        jPanel1.setPreferredSize(new java.awt.Dimension(831, 427));

        timecurrents.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        timecurrents.setText("0000-00-00 00:00:00 ");

        btnchangepass.setBackground(new java.awt.Color(220, 204, 96));
        btnchangepass.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnchangepass.setText("Change password");
        btnchangepass.setName("btnchangepass"); // NOI18N
        btnchangepass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnchangepassMouseClicked(evt);
            }
        });

        btnlogout.setBackground(new java.awt.Color(124, 121, 102));
        btnlogout.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.setName("btnchangepass"); // NOI18N
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnlogoutMousePressed(evt);
            }
        });

        username.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(195, 37, 39));
        username.setText("Name");

        jLabel1.setText("sdfsdfdsfsdafads");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(timecurrents)
                .addGap(212, 212, 212)
                .addComponent(btnchangepass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnlogout)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnlogout)
                        .addComponent(btnchangepass)
                        .addComponent(timecurrents))
                    .addComponent(username))
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMousePressed
        // TODO add your handling code here:
        // this.setOpacity(0.8f);
        this.setEnabled(false);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        frmlogout frmlogout= new frmlogout();
        frmlogout.setVisible(true);
        frmlogout.setAlwaysOnTop(true);
        frmlogout.setAccountSchool(accurent);
        frmlogout.setFrm0003s(this);
    }//GEN-LAST:event_btnlogoutMousePressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

            // TODO add your handling code here:
            
            Common com= new Common();
            ActionListener updateClockAction = new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        timecurrents.setText(com.getTimeCurrent());
                      }
            };
            Timer t = new Timer(1000, updateClockAction);
            t.start();
            username.setText(accurent.getNameshow());
            
//            Thread abc= new Thread(new Runnable() {
//                @Override
//                public void run() {
//                        timecurrents.setText(com.getTimeCurrent());             
//                }
//            });
//            while(true){
//                abc.start();
//                try {
//                    Thread.sleep(1000);
//                } catch (InterruptedException ex) {
//                    Logger.getLogger(frm0003.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
            
            
    }//GEN-LAST:event_formWindowActivated

    private void btnchangepassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnchangepassMouseClicked
           this.setEnabled(false);
           this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
           frmchangepassword frmchange= new frmchangepassword();
           frmchange.setVisible(true);
           frmchange.setAlwaysOnTop(true);
           frmchange.setAccountschool(accurent);
           frmchange.setFrm0003s(this);
    }//GEN-LAST:event_btnchangepassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm0003.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm0003.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm0003.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm0003.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm0003().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchangepass;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel timecurrents;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the accurent
     */
    public AccountSchool getAccurent() {
        return accurent;
    }

    /**
     * @param accurent the accurent to set
     */
    public void setAccurent(AccountSchool accurent) {
        this.accurent = accurent;
    }
}
